### ISSUE TITLE
Can't open PDF files from E-Mails

### ISSUE THREAD

**Issue by Preisschild** [JavaCafe01/PdfViewer#27]
### Issue Summary
When I open PDFs out of the AOSP E-Mail app, PDFViewer immediately crashes.

### Steps to Reproduce the Problem

Open a PDF with PDFViewer from the AOSP E-Mail app.

### Specifications

  - App Version: 3.0
  - Android Version: LineageOS 16.0 (Android 9.0)

**Comment by JavaCafe01** [comment]
Can you post any logs?

**Comment by PFayoux** [comment]
I reproduce the bug, I have the following error.

CursorWindow : Failed to read row 0 from column -1 from a CursorWindow which has 1 rows, 2 columns. Make sure the Cursor is initialized correctly before accessing data from it.

The bug is the following, the method getFileName() in MainActivity do this : 

cursor.getColumnIndex(OpenableColumns.DISPLAY_NAME) but if the cursor doesn't have a column that name is OpenableColumns.DISPLAY_NAME then it return -1.

Then doing cursor.getString(getColumnIndex(OpenableColumns.DISPLAY_NAME)) will return the error... and the app will crash.

You just have to patch by adding a  if(cursor.getColumnIndex(OpenableColumns.DISPLAY_NAME)  != 1) before (I guess...).

**Comment by PFayoux** [comment]
For information, the column name I have are `_id` and `_data`.

**Comment by Fs00** [comment]
I can confirm this is fixed (tested on a phone with AOSP Email), it can be closed @JavaCafe01
