### ISSUE TITLE
Blank document opens when opening pdf from firefox

### ISSUE THREAD

**Issue by AeliusSaionji** [JavaCafe01/PdfViewer#28]
As the title says. This app will not view pdfs opened from the web.

**Comment by JavaCafe01** [comment]
What happens specifically? I need some details or logs... Thanks!

**Comment by AeliusSaionji** [comment]
![](https://i.imgur.com/869hIDR.png)

**Comment by stkb** [comment]
I can add some info to this. Versions of PDF Viewer Plus up to 2.4 work fine with Firefox (as long as you set the storage permission for the app; if you don't, you get the blank screen as shown above). Since v2.5 it stopped working with Firefox, even if you've set the storage permission correctly.

I've only found Firefox to have this problem though, opening PDFs from other apps work fine.

[These](https://github.com/JavaCafe01/PdfViewer/compare/v2.4...v2.5) are the commits from v2.4 to 2.5, so it looks like this was probably "broken" in #4?

A workaround for now is to go back to version 2.4 (installed from the releases page).

**Comment by PFayoux** [comment]
I've made a patch for this issues, but to fix it I made the app download the pdf file.

From what I read here it could be possible to make firefox download the file before triggering an intent to call PdfViewer ? If that is possible I guess that should be better, if it is not possible I think my solution could be acceptable.

I used a AsyncTask as mentionned here https://github.com/barteksc/AndroidPdfViewer/issues/671#issuecomment-417570679

The thing is that PdfViewer will need to request INTERNET permission.

I can't do a push request right now, but when I will be able I will ;)

**Comment by AeliusSaionji** [comment]
This doesn't explain why it used to work, though? Did you have the internet permission before and pull it?

**Comment by PFayoux** [comment]
I don't really understand how it could have work bedore. PdfViewer don't have the possibility to download a PDF file from an URI, and if it was working that would have mean that Firefox was downloading the PDF file before triggering an intent to launch it in PdfViewer.

The only way I see patching this is making PdfViewer able to download a pdf file, I currently did a patch that was working fine with HTTP request, but I just didn't know how to make it work for HTTPS (of course making it work with HTTPS would mean making it safe by verifying TLS certificate from the system AC store).

I will still work on it, if anyone want to help, I would be please to have any help for the HTTPS support.

I don't know if giving internet and write external storage permission to PdfViewer is something that is wanted by the community (and main developer) if it can solve this issue ?

**Comment by stkb** [comment]
> that would have mean that Firefox was downloading the PDF file before triggering an intent to launch it in PdfViewer.

I believe that is the case, yes
